# Generated by Django 5.2.8 on 2025-11-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_birthday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followings',
            new_name='following',
        ),
    ]
